# Generated by Django 5.2.4 on 2025-08-24 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_d',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='books.quiz')),
            ],
        ),
    ]
