# Generated by Django 5.2.4 on 2025-09-09 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('suit_number', models.CharField(max_length=100, unique=True)),
                ('number_of_pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('summary', models.TextField()),
                ('citation', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_copies', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_copies', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='books.topic')),
            ],
        ),
    ]
